In [1]:
import pandas_datareader.data as web
import pandas as pd
import requests
import matplotlib
import datetime as dt

In [2]:
df = pd.read_csv("../data/raw/OSullivan_Capital.csv")
df.head()

,ASX Listed Equities,Unnamed: 1,Unnamed: 2
0,Stock,Proportion of Portfolio,Notes
1,A2M,0.58%,NaN
2,ART,0.07%,NaN
3,ASIA,2.10%,- ETF composed of Asian tech stocks
4,ASN,0.02%,NaN

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ASX Listed Equities  57 non-null     object
 1   Unnamed: 1           56 non-null     object
 2   Unnamed: 2           10 non-null     object
dtypes: object(3)
memory usage: 1.5+ KB

In [4]:
start = dt.datetime(2014,1,1)
end = dt.datetime.now()

In [8]:
us_tickers = ["ACN", "AMZN", "BA", "CRM", "ESPR", "EXAI", "ICLN", "INDA", "INTC", "ISRG", "KLAC", "KLIC", "LICY", "LMT", "MDB", "MSFT", "NVDA", "PLTR", "SAP", "TEAM", "VGT"]

In [10]:
# stock_df = pd.DataFrame()
# for ticker in us_tickers:
#     df2 = web.DataReader(ticker, "yahoo", start, end)
#     df[ticker] = df2["Adj Close"]

In [11]:
# stock_df = web.DataReader(us_stock_list, 'yahoo', start, end)

In [18]:
from pandas_datareader import data as pdr
import yfinance as yf
yf.pdr_override()
y_symbols = us_tickers
from datetime import datetime
startdate = datetime(2015,1,1)
enddate = datetime.now()
data = pdr.get_data_yahoo(y_symbols, start=startdate, end=enddate)

[*********************100%%**********************]  21 of 21 completed

In [20]:
data.tail()

Price        Adj Close                                                         \
Ticker             ACN        AMZN          BA         CRM  ESPR  EXAI   ICLN
Date
2024-05-28  297.730011  182.149994  175.080002  269.829987  2.10  4.76  15.08
2024-05-29  293.769989  182.020004  171.649994  271.619995  2.17  4.67  14.83
2024-05-30  284.799988  179.320007  172.750000  218.009995  2.29  4.94  15.04
2024-05-31  282.290009  176.440002  177.610001  234.440002  2.16  5.30  14.97
2024-06-03  281.760010  178.339996  184.570007  236.619995  2.24  5.42  15.08

Price                                         ...  Volume                     \
Ticker           INDA       INTC        ISRG  ...    KLIC      LICY      LMT
Date                                          ...
2024-05-28  53.560001  31.059999  401.029999  ...  287500  649675.0  1150400
2024-05-29  53.279999  30.129999  398.399994  ...  363000  468933.0  1268000
2024-05-30  53.029999  30.190001  403.390015  ...  478500  585798.0  1173600
2024-05-31  53.009998  30.850000  402.119995  ...  665600  267170.0  1651600
2024-06-03  54.799999  30.290001  403.859985  ...  286000  201964.0   990100

Price                                                                       \
Ticker             MDB      MSFT      NVDA        PLTR      SAP       TEAM
Date
2024-05-28   1717400.0  15718000  65272800  26274200.0   794900  3895900.0
2024-05-29   1154100.0  15517100  55744200  24834200.0   747400  4530200.0
2024-05-30   4801300.0  28424800  48735000  47583100.0  1950600  3053700.0
2024-05-31  10987900.0  47995300  61326300  44416100.0   848700  4389700.0
2024-06-03   4868400.0  17434200  43616800  33782100.0   754600  1550300.0

Price
Ticker         VGT
Date
2024-05-28  372900
2024-05-29  312500
2024-05-30  547400
2024-05-31  546000
2024-06-03  386300

[5 rows x 126 columns]

In [22]:
import numpy as np
return1 = np.log(data/data.shift())

In [24]:
return1.head()

Price      Adj Close                                                         \
Ticker           ACN      AMZN        BA       CRM      ESPR EXAI      ICLN
Date
2015-01-02       NaN       NaN       NaN       NaN       NaN  NaN       NaN
2015-01-05 -0.017029 -0.020731 -0.006950 -0.018227  0.069332  NaN -0.021773
2015-01-06 -0.007239 -0.023098 -0.011848 -0.016816 -0.018731  NaN -0.002099
2015-01-07  0.020772  0.010544  0.015406 -0.004731  0.081868  NaN  0.009409
2015-01-08  0.015134  0.006813  0.017528  0.028742  0.018731  NaN  0.023652

Price                                     ...    Volume                     \
Ticker          INDA      INTC      ISRG  ...      KLIC LICY       LMT MDB
Date                                      ...
2015-01-02       NaN       NaN       NaN  ...       NaN  NaN       NaN NaN
2015-01-05 -0.016255 -0.011340 -0.021541  ...  0.623253  NaN  0.512620 NaN
2015-01-06 -0.030907 -0.018813  0.010482  ... -0.107016  NaN -0.222447 NaN
2015-01-07  0.019471  0.020759  0.005468  ... -0.693147  NaN -0.246999 NaN
2015-01-08  0.026375  0.018430  0.019629  ...  0.765573  NaN  0.728147 NaN

Price
Ticker          MSFT      NVDA PLTR       SAP TEAM       VGT
Date
2015-01-02       NaN       NaN  NaN       NaN  NaN       NaN
2015-01-05  0.351569  0.554637  NaN  0.898462  NaN  0.545757
2015-01-06 -0.084810 -0.000950  NaN -0.126781  NaN -0.152151
2015-01-07 -0.224661  0.486881  NaN  0.002836  NaN -0.233117
2015-01-08  0.018078 -0.125756  NaN -0.224645  NaN  0.602138

[5 rows x 126 columns]

In [26]:
return1.dropna(inplace=True)

In [27]:
return1.head()

Price      Adj Close                                                    \
Ticker           ACN      AMZN        BA       CRM      ESPR      EXAI
Date
2021-10-04 -0.016668 -0.028885 -0.009827 -0.016114 -0.016068 -0.070312
2021-10-05  0.017468  0.009740  0.002811  0.003354 -0.106972 -0.102462
2021-10-06  0.000215  0.012652  0.002537  0.012796 -0.035735 -0.022622
2021-10-07  0.003254  0.012315  0.006601 -0.002510 -0.001969  0.004923
2021-10-08 -0.003254 -0.004191 -0.000397 -0.007677  0.008828  0.071074

Price                                               ...    Volume            \
Ticker          ICLN      INDA      INTC      ISRG  ...      KLIC      LICY
Date                                                ...
2021-10-04 -0.026532 -0.004895 -0.007267 -0.039399  ...  0.574277 -0.066866
2021-10-05  0.001885  0.011789  0.008937  0.020106  ... -0.001575  0.223842
2021-10-06  0.002351 -0.009746  0.000556  0.014647  ... -0.391597  1.716508
2021-10-07  0.010281  0.005900  0.003698  0.010100  ...  0.183055 -0.711297
2021-10-08 -0.007935 -0.000812 -0.006852 -0.029393  ...  0.289810 -0.893402

Price                                                                   \
Ticker           LMT       MDB      MSFT      NVDA      PLTR       SAP
Date
2021-10-04  0.160320  0.809359  0.041167  0.360678  0.355906 -0.068598
2021-10-05 -0.237122 -0.896627 -0.226641 -0.213161  0.189901  0.426214
2021-10-06  0.112899  0.000771  0.113702  0.062190  0.794155  0.001859
2021-10-07  0.046027 -0.067535 -0.315268 -0.145651 -1.169400 -0.207870
2021-10-08 -0.305032  0.591946 -0.144272 -0.529774  0.021371 -0.079384

Price
Ticker          TEAM       VGT
Date
2021-10-04 -0.036127  0.240257
2021-10-05 -0.242786 -0.607739
2021-10-06  0.047164  1.381554
2021-10-07 -0.177195 -0.134452
2021-10-08 -0.113092 -1.894647

[5 rows x 126 columns]

In [35]:
Er = np.array(return1.describe().loc['mean'])
std = np.array(return1.describe().loc['std'])
var = std**2

In [37]:
varcover1 = return1.cov()
varcover1

Price            Adj Close                                              \
Ticker                 ACN      AMZN        BA       CRM          ESPR
Price     Ticker
Adj Close ACN     0.000296  0.000232  0.000150  0.000232  1.038844e-04
          AMZN    0.000232  0.000600  0.000219  0.000351  1.447173e-04
          BA      0.000150  0.000219  0.000572  0.000201  1.893487e-04
          CRM     0.000232  0.000351  0.000201  0.000632  2.189576e-04
          ESPR    0.000104  0.000145  0.000189  0.000219  4.443871e-03
...                    ...       ...       ...       ...           ...
Volume    NVDA    0.000077 -0.000096 -0.000233  0.000319 -5.597660e-04
          PLTR   -0.000113  0.000024 -0.000389 -0.000335 -4.191447e-07
          SAP    -0.000574 -0.000580 -0.000442 -0.000726 -6.193346e-04
          TEAM   -0.000065 -0.000124 -0.000470 -0.000319 -5.153038e-04
          VGT    -0.000767 -0.000821 -0.002099 -0.000304 -1.713889e-03

Price                                                               ...  \
Ticker                EXAI      ICLN      INDA      INTC      ISRG  ...
Price     Ticker                                                    ...
Adj Close ACN     0.000265  0.000148  0.000083  0.000185  0.000217  ...
          AMZN    0.000407  0.000204  0.000106  0.000236  0.000277  ...
          BA      0.000348  0.000196  0.000106  0.000210  0.000192  ...
          CRM     0.000381  0.000204  0.000100  0.000237  0.000262  ...
          ESPR    0.000522  0.000284  0.000104  0.000080  0.000176  ...
...                    ...       ...       ...       ...       ...  ...
Volume    NVDA   -0.000176 -0.000025 -0.000088  0.000054 -0.000084  ...
          PLTR   -0.001249 -0.000372 -0.000057  0.000112 -0.000232  ...
          SAP    -0.000051  0.000024 -0.000168  0.000500 -0.000477  ...
          TEAM    0.000984 -0.000161 -0.000324  0.000436 -0.000185  ...
          VGT    -0.001662 -0.000478 -0.000597 -0.000382 -0.001028  ...

Price               Volume                                                    \
Ticker                KLIC      LICY       LMT       MDB      MSFT      NVDA
Price     Ticker
Adj Close ACN    -0.000364  0.000291 -0.000236 -0.000108 -0.000371  0.000077
          AMZN   -0.000427  0.000525 -0.000292 -0.000019 -0.000812 -0.000096
          BA     -0.000354 -0.000803 -0.000124  0.000210 -0.000739 -0.000233
          CRM    -0.000391  0.000484 -0.000319 -0.000404 -0.000650  0.000319
          ESPR   -0.002152 -0.000135 -0.000820  0.000979 -0.000651 -0.000560
...                    ...       ...       ...       ...       ...       ...
Volume    NVDA    0.025464  0.010859  0.030876  0.034659  0.027195  0.073571
          PLTR    0.021142  0.033824  0.026054  0.039539  0.029243  0.025464
          SAP     0.037839  0.010802  0.031196  0.036053  0.029277  0.013680
          TEAM    0.058553  0.022517  0.042558  0.067786  0.045494  0.030766
          VGT     0.024410  0.005280  0.028512  0.031767  0.036265  0.027155

Price
Ticker                    PLTR       SAP      TEAM       VGT
Price     Ticker
Adj Close ACN    -1.133722e-04 -0.000574 -0.000065 -0.000767
          AMZN    2.369906e-05 -0.000580 -0.000124 -0.000821
          BA     -3.894218e-04 -0.000442 -0.000470 -0.002099
          CRM    -3.352495e-04 -0.000726 -0.000319 -0.000304
          ESPR   -4.191447e-07 -0.000619 -0.000515 -0.001714
...                        ...       ...       ...       ...
Volume    NVDA    2.546397e-02  0.013680  0.030766  0.027155
          PLTR    1.179670e-01  0.019923  0.028439  0.041045
          SAP     1.992344e-02  0.136601  0.030607  0.020046
          TEAM    2.843892e-02  0.030607  0.182557  0.011674
          VGT     4.104467e-02  0.020046  0.011674  0.346887

[126 rows x 126 columns]